// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireRegistrationLock = `-- name: AcquireRegistrationLock :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::text || ':' || $2::text, 0)
)
`

type AcquireRegistrationLockParams struct {
	DeviceInstallationID string `json:"device_installation_id"`
	IdempotencyKey       string `json:"idempotency_key"`
}

func (q *Queries) AcquireRegistrationLock(ctx context.Context, arg AcquireRegistrationLockParams) error {
	_, err := q.db.Exec(ctx, acquireRegistrationLock, arg.DeviceInstallationID, arg.IdempotencyKey)
	return err
}

const approveUserAfterReview = `-- name: ApproveUserAfterReview :execrows
UPDATE mineg.users
SET reviewed_at = COALESCE(reviewed_at, $2),
    reviewed_by = COALESCE(reviewed_by, $3),
    status = 'APPROVED',
    updated_at = $2
WHERE id = $1 AND status = 'PENDING'
`

type ApproveUserAfterReviewParams struct {
	ID         pgtype.UUID        `json:"id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ReviewedBy pgtype.UUID        `json:"reviewed_by"`
}

func (q *Queries) ApproveUserAfterReview(ctx context.Context, arg ApproveUserAfterReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveUserAfterReview, arg.ID, arg.UpdatedAt, arg.ReviewedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeAvatarUpload = `-- name: CompleteAvatarUpload :execrows
UPDATE mineg.avatar_uploads
SET state = 'READY', completed_at = $3
WHERE id = $1 AND user_id = $2 AND state = 'PENDING' AND expires_at > $3
`

type CompleteAvatarUploadParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CompleteAvatarUpload(ctx context.Context, arg CompleteAvatarUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAvatarUpload, arg.ID, arg.UserID, arg.CompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*) FROM mineg.admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO mineg.admin_sessions (
    admin_user_id, session_token_hash, csrf_token_hash, absolute_expires_at
) VALUES ($1, $2, $3, $4)
RETURNING id, admin_user_id, created_at, last_active_at, absolute_expires_at
`

type CreateAdminSessionParams struct {
	AdminUserID       pgtype.UUID        `json:"admin_user_id"`
	SessionTokenHash  []byte             `json:"session_token_hash"`
	CsrfTokenHash     []byte             `json:"csrf_token_hash"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

type CreateAdminSessionRow struct {
	ID                pgtype.UUID        `json:"id"`
	AdminUserID       pgtype.UUID        `json:"admin_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (CreateAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.AdminUserID,
		arg.SessionTokenHash,
		arg.CsrfTokenHash,
		arg.AbsoluteExpiresAt,
	)
	var i CreateAdminSessionRow
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO mineg.admin_users (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, password_hash, created_at, disabled_at
`

type CreateAdminUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (MinegAdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Username, arg.PasswordHash)
	var i MinegAdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const createApprovalRequest = `-- name: CreateApprovalRequest :execrows
INSERT INTO mineg.approval_requests (admin_user_id, idempotency_key, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (admin_user_id, idempotency_key) DO NOTHING
`

type CreateApprovalRequestParams struct {
	AdminUserID    pgtype.UUID `json:"admin_user_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, createApprovalRequest, arg.AdminUserID, arg.IdempotencyKey, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAvatarUpload = `-- name: CreateAvatarUpload :one
INSERT INTO mineg.avatar_uploads(
    id, user_id, idempotency_key, object_key, content_type, source_size,
    display_size, width, height, content_sha256, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id, idempotency_key) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, idempotency_key, object_key, content_type, source_size, display_size, width, height, content_sha256, state, expires_at, completed_at, created_at
`

type CreateAvatarUploadParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	ObjectKey      string             `json:"object_key"`
	ContentType    string             `json:"content_type"`
	SourceSize     int64              `json:"source_size"`
	DisplaySize    int64              `json:"display_size"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	ContentSha256  []byte             `json:"content_sha256"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAvatarUpload(ctx context.Context, arg CreateAvatarUploadParams) (MinegAvatarUpload, error) {
	row := q.db.QueryRow(ctx, createAvatarUpload,
		arg.ID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.ObjectKey,
		arg.ContentType,
		arg.SourceSize,
		arg.DisplaySize,
		arg.Width,
		arg.Height,
		arg.ContentSha256,
		arg.ExpiresAt,
	)
	var i MinegAvatarUpload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.ObjectKey,
		&i.ContentType,
		&i.SourceSize,
		&i.DisplaySize,
		&i.Width,
		&i.Height,
		&i.ContentSha256,
		&i.State,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRegistrationRequest = `-- name: CreateRegistrationRequest :exec
INSERT INTO mineg.registration_requests (
    device_installation_id, idempotency_key, request_hash, user_id, rotation_family_id
) VALUES ($1, $2, $3, $4, $5)
`

type CreateRegistrationRequestParams struct {
	DeviceInstallationID string      `json:"device_installation_id"`
	IdempotencyKey       string      `json:"idempotency_key"`
	RequestHash          []byte      `json:"request_hash"`
	UserID               pgtype.UUID `json:"user_id"`
	RotationFamilyID     pgtype.UUID `json:"rotation_family_id"`
}

func (q *Queries) CreateRegistrationRequest(ctx context.Context, arg CreateRegistrationRequestParams) error {
	_, err := q.db.Exec(ctx, createRegistrationRequest,
		arg.DeviceInstallationID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.UserID,
		arg.RotationFamilyID,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO mineg.users (phone_e164, password_hash, nickname)
VALUES ($1, $2, $3)
RETURNING id, phone_e164, password_hash, status, nickname, avatar_url,
          reviewed_at, reviewed_by, created_at, updated_at
`

type CreateUserParams struct {
	PhoneE164    string `json:"phone_e164"`
	PasswordHash string `json:"password_hash"`
	Nickname     string `json:"nickname"`
}

type CreateUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	PhoneE164    string             `json:"phone_e164"`
	PasswordHash string             `json:"password_hash"`
	Status       string             `json:"status"`
	Nickname     string             `json:"nickname"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy   pgtype.UUID        `json:"reviewed_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneE164, arg.PasswordHash, arg.Nickname)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.PasswordHash,
		&i.Status,
		&i.Nickname,
		&i.AvatarUrl,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO mineg.user_sessions (
    user_id, device_id, rotation_family_id, access_token_hash, refresh_token_hash,
    access_expires_at, refresh_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, device_id, rotation_family_id, access_expires_at,
          refresh_expires_at, rotated_at, revoked_at, created_at, last_active_at
`

type CreateUserSessionParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	RotationFamilyID pgtype.UUID        `json:"rotation_family_id"`
	AccessTokenHash  []byte             `json:"access_token_hash"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
}

type CreateUserSessionRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	RotationFamilyID pgtype.UUID        `json:"rotation_family_id"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
	RotatedAt        pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (CreateUserSessionRow, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.DeviceID,
		arg.RotationFamilyID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i CreateUserSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RotationFamilyID,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const ensureFixedFamilyMembership = `-- name: EnsureFixedFamilyMembership :one
WITH family_lock AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended('mineg-fixed-household', 6))
), next_slot AS (
    SELECT min(slots.member_slot)::smallint AS member_slot
    FROM (VALUES (1::smallint), (2::smallint)) AS slots(member_slot), family_lock
    WHERE NOT EXISTS (
        SELECT 1 FROM mineg.family_memberships member
        WHERE member.family_id = '00000000-0000-4000-8000-000000000001'
          AND member.member_slot = slots.member_slot
    )
), resolved_slot AS (
    SELECT COALESCE(
        (SELECT existing.member_slot FROM mineg.family_memberships AS existing WHERE existing.user_id = $1),
        next_slot.member_slot
    ) AS member_slot
    FROM next_slot
), ensured AS (
    INSERT INTO mineg.family_memberships(user_id, member_slot)
    SELECT $1, resolved_slot.member_slot
    FROM resolved_slot
    WHERE resolved_slot.member_slot IS NOT NULL
    ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
    RETURNING user_id
)
SELECT EXISTS(SELECT 1 FROM ensured) AS ensured
`

func (q *Queries) EnsureFixedFamilyMembership(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ensureFixedFamilyMembership, userID)
	var ensured bool
	err := row.Scan(&ensured)
	return ensured, err
}

const findAdminByUsername = `-- name: FindAdminByUsername :one
SELECT id, username, password_hash, created_at, disabled_at
FROM mineg.admin_users
WHERE username = $1
`

func (q *Queries) FindAdminByUsername(ctx context.Context, username string) (MinegAdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByUsername, username)
	var i MinegAdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const findAdminSessionForUpdate = `-- name: FindAdminSessionForUpdate :one
SELECT sessions.id, sessions.admin_user_id, sessions.csrf_token_hash,
       sessions.created_at, sessions.last_active_at, sessions.absolute_expires_at,
       sessions.revoked_at, admins.username, admins.disabled_at
FROM mineg.admin_sessions sessions
JOIN mineg.admin_users admins ON admins.id = sessions.admin_user_id
WHERE sessions.session_token_hash = $1
FOR UPDATE OF sessions
`

type FindAdminSessionForUpdateRow struct {
	ID                pgtype.UUID        `json:"id"`
	AdminUserID       pgtype.UUID        `json:"admin_user_id"`
	CsrfTokenHash     []byte             `json:"csrf_token_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	Username          string             `json:"username"`
	DisabledAt        pgtype.Timestamptz `json:"disabled_at"`
}

func (q *Queries) FindAdminSessionForUpdate(ctx context.Context, sessionTokenHash []byte) (FindAdminSessionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findAdminSessionForUpdate, sessionTokenHash)
	var i FindAdminSessionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.Username,
		&i.DisabledAt,
	)
	return i, err
}

const findApproval = `-- name: FindApproval :one
SELECT id, phone_e164, status, reviewed_at, created_at
FROM mineg.users
WHERE id = $1
`

type FindApprovalRow struct {
	ID         pgtype.UUID        `json:"id"`
	PhoneE164  string             `json:"phone_e164"`
	Status     string             `json:"status"`
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindApproval(ctx context.Context, id pgtype.UUID) (FindApprovalRow, error) {
	row := q.db.QueryRow(ctx, findApproval, id)
	var i FindApprovalRow
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Status,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findApprovalRequest = `-- name: FindApprovalRequest :one
SELECT admin_user_id, idempotency_key, user_id, created_at
FROM mineg.approval_requests
WHERE admin_user_id = $1 AND idempotency_key = $2
`

type FindApprovalRequestParams struct {
	AdminUserID    pgtype.UUID `json:"admin_user_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) FindApprovalRequest(ctx context.Context, arg FindApprovalRequestParams) (MinegApprovalRequest, error) {
	row := q.db.QueryRow(ctx, findApprovalRequest, arg.AdminUserID, arg.IdempotencyKey)
	var i MinegApprovalRequest
	err := row.Scan(
		&i.AdminUserID,
		&i.IdempotencyKey,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const findAvatarUploadForUpdate = `-- name: FindAvatarUploadForUpdate :one
SELECT id, user_id, idempotency_key, object_key, content_type, source_size, display_size, width, height, content_sha256, state, expires_at, completed_at, created_at FROM mineg.avatar_uploads
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type FindAvatarUploadForUpdateParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) FindAvatarUploadForUpdate(ctx context.Context, arg FindAvatarUploadForUpdateParams) (MinegAvatarUpload, error) {
	row := q.db.QueryRow(ctx, findAvatarUploadForUpdate, arg.ID, arg.UserID)
	var i MinegAvatarUpload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.ObjectKey,
		&i.ContentType,
		&i.SourceSize,
		&i.DisplaySize,
		&i.Width,
		&i.Height,
		&i.ContentSha256,
		&i.State,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findRegistrationRequest = `-- name: FindRegistrationRequest :one
SELECT device_installation_id, idempotency_key, request_hash, user_id, rotation_family_id, created_at
FROM mineg.registration_requests
WHERE device_installation_id = $1 AND idempotency_key = $2
`

type FindRegistrationRequestParams struct {
	DeviceInstallationID string `json:"device_installation_id"`
	IdempotencyKey       string `json:"idempotency_key"`
}

func (q *Queries) FindRegistrationRequest(ctx context.Context, arg FindRegistrationRequestParams) (MinegRegistrationRequest, error) {
	row := q.db.QueryRow(ctx, findRegistrationRequest, arg.DeviceInstallationID, arg.IdempotencyKey)
	var i MinegRegistrationRequest
	err := row.Scan(
		&i.DeviceInstallationID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.UserID,
		&i.RotationFamilyID,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, phone_e164, password_hash, status, nickname, avatar_url,
       reviewed_at, reviewed_by, created_at, updated_at, avatar_upload_id, profile_version
FROM mineg.users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (MinegUser, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i MinegUser
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.PasswordHash,
		&i.Status,
		&i.Nickname,
		&i.AvatarUrl,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUploadID,
		&i.ProfileVersion,
	)
	return i, err
}

const findUserByPhone = `-- name: FindUserByPhone :one
SELECT id, phone_e164, password_hash, status, nickname, avatar_url,
       reviewed_at, reviewed_by, created_at, updated_at
FROM mineg.users
WHERE phone_e164 = $1
`

type FindUserByPhoneRow struct {
	ID           pgtype.UUID        `json:"id"`
	PhoneE164    string             `json:"phone_e164"`
	PasswordHash string             `json:"password_hash"`
	Status       string             `json:"status"`
	Nickname     string             `json:"nickname"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy   pgtype.UUID        `json:"reviewed_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindUserByPhone(ctx context.Context, phoneE164 string) (FindUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, phoneE164)
	var i FindUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.PasswordHash,
		&i.Status,
		&i.Nickname,
		&i.AvatarUrl,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserSessionByAccess = `-- name: FindUserSessionByAccess :one
SELECT sessions.id, sessions.user_id, sessions.device_id, sessions.rotation_family_id,
       sessions.access_expires_at, sessions.refresh_expires_at, sessions.rotated_at,
       sessions.revoked_at, sessions.created_at, sessions.last_active_at, users.status
FROM mineg.user_sessions sessions
JOIN mineg.users users ON users.id = sessions.user_id
WHERE sessions.access_token_hash = $1
`

type FindUserSessionByAccessRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	RotationFamilyID pgtype.UUID        `json:"rotation_family_id"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
	RotatedAt        pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
	Status           string             `json:"status"`
}

func (q *Queries) FindUserSessionByAccess(ctx context.Context, accessTokenHash []byte) (FindUserSessionByAccessRow, error) {
	row := q.db.QueryRow(ctx, findUserSessionByAccess, accessTokenHash)
	var i FindUserSessionByAccessRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RotationFamilyID,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.Status,
	)
	return i, err
}

const findUserSessionByRefreshForUpdate = `-- name: FindUserSessionByRefreshForUpdate :one
SELECT sessions.id, sessions.user_id, sessions.device_id, sessions.rotation_family_id,
       sessions.access_expires_at, sessions.refresh_expires_at, sessions.rotated_at,
       sessions.revoked_at, sessions.created_at, sessions.last_active_at, users.status
FROM mineg.user_sessions sessions
JOIN mineg.users users ON users.id = sessions.user_id
WHERE sessions.refresh_token_hash = $1
FOR UPDATE OF sessions
`

type FindUserSessionByRefreshForUpdateRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	RotationFamilyID pgtype.UUID        `json:"rotation_family_id"`
	AccessExpiresAt  pgtype.Timestamptz `json:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `json:"refresh_expires_at"`
	RotatedAt        pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
	Status           string             `json:"status"`
}

func (q *Queries) FindUserSessionByRefreshForUpdate(ctx context.Context, refreshTokenHash []byte) (FindUserSessionByRefreshForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findUserSessionByRefreshForUpdate, refreshTokenHash)
	var i FindUserSessionByRefreshForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.RotationFamilyID,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.Status,
	)
	return i, err
}

const getReadyAvatar = `-- name: GetReadyAvatar :one
SELECT upload.id, upload.user_id, upload.object_key, upload.content_type,
       upload.display_size, upload.content_sha256, upload.completed_at
FROM mineg.users user_account
JOIN mineg.avatar_uploads upload ON upload.id = user_account.avatar_upload_id
WHERE user_account.id = $1 AND upload.state = 'READY'
`

type GetReadyAvatarRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ObjectKey     string             `json:"object_key"`
	ContentType   string             `json:"content_type"`
	DisplaySize   int64              `json:"display_size"`
	ContentSha256 []byte             `json:"content_sha256"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetReadyAvatar(ctx context.Context, id pgtype.UUID) (GetReadyAvatarRow, error) {
	row := q.db.QueryRow(ctx, getReadyAvatar, id)
	var i GetReadyAvatarRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.ContentType,
		&i.DisplaySize,
		&i.ContentSha256,
		&i.CompletedAt,
	)
	return i, err
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT id, phone_e164, created_at
FROM mineg.users
WHERE reviewed_at IS NULL
  AND ($1::timestamptz IS NULL OR (created_at, id) > ($1::timestamptz, $2::uuid))
ORDER BY created_at ASC, id ASC
LIMIT $3
`

type ListPendingApprovalsParams struct {
	Column1 pgtype.Timestamptz `json:"column_1"`
	Column2 pgtype.UUID        `json:"column_2"`
	Limit   int32              `json:"limit"`
}

type ListPendingApprovalsRow struct {
	ID        pgtype.UUID        `json:"id"`
	PhoneE164 string             `json:"phone_e164"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingApprovals(ctx context.Context, arg ListPendingApprovalsParams) ([]ListPendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingApprovalsRow
	for rows.Next() {
		var i ListPendingApprovalsRow
		if err := rows.Scan(&i.ID, &i.PhoneE164, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserReviewed = `-- name: MarkUserReviewed :execrows
UPDATE mineg.users
SET reviewed_at = COALESCE(reviewed_at, $2), reviewed_by = COALESCE(reviewed_by, $3), updated_at = $2
WHERE id = $1 AND reviewed_at IS NULL
`

type MarkUserReviewedParams struct {
	ID         pgtype.UUID        `json:"id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ReviewedBy pgtype.UUID        `json:"reviewed_by"`
}

func (q *Queries) MarkUserReviewed(ctx context.Context, arg MarkUserReviewedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUserReviewed, arg.ID, arg.UpdatedAt, arg.ReviewedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUserSessionRotated = `-- name: MarkUserSessionRotated :exec
UPDATE mineg.user_sessions SET rotated_at = $2, last_active_at = $2 WHERE id = $1
`

type MarkUserSessionRotatedParams struct {
	ID        pgtype.UUID        `json:"id"`
	RotatedAt pgtype.Timestamptz `json:"rotated_at"`
}

func (q *Queries) MarkUserSessionRotated(ctx context.Context, arg MarkUserSessionRotatedParams) error {
	_, err := q.db.Exec(ctx, markUserSessionRotated, arg.ID, arg.RotatedAt)
	return err
}

const recordAgreement = `-- name: RecordAgreement :exec
INSERT INTO mineg.user_agreements (
    user_id, terms_version, privacy_version, device_installation_id
) VALUES ($1, $2, $3, $4)
`

type RecordAgreementParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	TermsVersion         string      `json:"terms_version"`
	PrivacyVersion       string      `json:"privacy_version"`
	DeviceInstallationID string      `json:"device_installation_id"`
}

func (q *Queries) RecordAgreement(ctx context.Context, arg RecordAgreementParams) error {
	_, err := q.db.Exec(ctx, recordAgreement,
		arg.UserID,
		arg.TermsVersion,
		arg.PrivacyVersion,
		arg.DeviceInstallationID,
	)
	return err
}

const recordAuditEvent = `-- name: RecordAuditEvent :exec
INSERT INTO mineg.audit_events (
    actor_type, actor_id, action, target_type, target_id, result, request_id, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordAuditEventParams struct {
	ActorType  string      `json:"actor_type"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType string      `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
	Result     string      `json:"result"`
	RequestID  string      `json:"request_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error {
	_, err := q.db.Exec(ctx, recordAuditEvent,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Result,
		arg.RequestID,
		arg.Metadata,
	)
	return err
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE mineg.admin_sessions SET revoked_at = COALESCE(revoked_at, $2) WHERE id = $1
`

type RevokeAdminSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE mineg.user_sessions SET revoked_at = COALESCE(revoked_at, $2) WHERE id = $1
`

type RevokeUserSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) error {
	_, err := q.db.Exec(ctx, revokeUserSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeUserSessionFamily = `-- name: RevokeUserSessionFamily :exec
UPDATE mineg.user_sessions
SET revoked_at = COALESCE(revoked_at, $2)
WHERE rotation_family_id = $1
`

type RevokeUserSessionFamilyParams struct {
	RotationFamilyID pgtype.UUID        `json:"rotation_family_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeUserSessionFamily(ctx context.Context, arg RevokeUserSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessionFamily, arg.RotationFamilyID, arg.RevokedAt)
	return err
}

const rotateAdminCSRF = `-- name: RotateAdminCSRF :exec
UPDATE mineg.admin_sessions SET csrf_token_hash = $2, last_active_at = $3 WHERE id = $1
`

type RotateAdminCSRFParams struct {
	ID            pgtype.UUID        `json:"id"`
	CsrfTokenHash []byte             `json:"csrf_token_hash"`
	LastActiveAt  pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) RotateAdminCSRF(ctx context.Context, arg RotateAdminCSRFParams) error {
	_, err := q.db.Exec(ctx, rotateAdminCSRF, arg.ID, arg.CsrfTokenHash, arg.LastActiveAt)
	return err
}

const setUserAvatar = `-- name: SetUserAvatar :execrows
UPDATE mineg.users
SET avatar_upload_id = $2, avatar_url = NULL,
    profile_version = profile_version + 1, updated_at = $3
WHERE id = $1 AND status = 'APPROVED'
`

type SetUserAvatarParams struct {
	ID             pgtype.UUID        `json:"id"`
	AvatarUploadID pgtype.UUID        `json:"avatar_upload_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserAvatar, arg.ID, arg.AvatarUploadID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAdminSession = `-- name: TouchAdminSession :exec
UPDATE mineg.admin_sessions SET last_active_at = $2 WHERE id = $1
`

type TouchAdminSessionParams struct {
	ID           pgtype.UUID        `json:"id"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

func (q *Queries) TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) error {
	_, err := q.db.Exec(ctx, touchAdminSession, arg.ID, arg.LastActiveAt)
	return err
}

const updateRegistrationFamily = `-- name: UpdateRegistrationFamily :exec
UPDATE mineg.registration_requests
SET rotation_family_id = $3
WHERE device_installation_id = $1 AND idempotency_key = $2
`

type UpdateRegistrationFamilyParams struct {
	DeviceInstallationID string      `json:"device_installation_id"`
	IdempotencyKey       string      `json:"idempotency_key"`
	RotationFamilyID     pgtype.UUID `json:"rotation_family_id"`
}

func (q *Queries) UpdateRegistrationFamily(ctx context.Context, arg UpdateRegistrationFamilyParams) error {
	_, err := q.db.Exec(ctx, updateRegistrationFamily, arg.DeviceInstallationID, arg.IdempotencyKey, arg.RotationFamilyID)
	return err
}

const updateUserNickname = `-- name: UpdateUserNickname :one
UPDATE mineg.users
SET nickname = $2, profile_version = profile_version + 1, updated_at = $3
WHERE id = $1 AND status = 'APPROVED'
RETURNING id, phone_e164, password_hash, status, nickname, avatar_url,
          reviewed_at, reviewed_by, created_at, updated_at, avatar_upload_id, profile_version
`

type UpdateUserNicknameParams struct {
	ID        pgtype.UUID        `json:"id"`
	Nickname  string             `json:"nickname"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) (MinegUser, error) {
	row := q.db.QueryRow(ctx, updateUserNickname, arg.ID, arg.Nickname, arg.UpdatedAt)
	var i MinegUser
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.PasswordHash,
		&i.Status,
		&i.Nickname,
		&i.AvatarUrl,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUploadID,
		&i.ProfileVersion,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO mineg.devices (user_id, installation_id, platform)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, installation_id) DO UPDATE
SET platform = EXCLUDED.platform, last_active_at = CURRENT_TIMESTAMP
RETURNING id, user_id, installation_id, platform, last_active_at, created_at
`

type UpsertDeviceParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	InstallationID string      `json:"installation_id"`
	Platform       string      `json:"platform"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (MinegDevice, error) {
	row := q.db.QueryRow(ctx, upsertDevice, arg.UserID, arg.InstallationID, arg.Platform)
	var i MinegDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.Platform,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}
