// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: platform.sql

package dbgen

import (
	"context"
)

const databaseTime = `-- name: DatabaseTime :one
SELECT CURRENT_TIMESTAMP AS database_time
`

func (q *Queries) DatabaseTime(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var database_time interface{}
	err := row.Scan(&database_time)
	return database_time, err
}
