// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: private_media.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTrashIdempotencyLock = `-- name: AcquireTrashIdempotencyLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':' || $2::text, 0))
`

type AcquireTrashIdempotencyLockParams struct {
	OwnerID        string `json:"owner_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) AcquireTrashIdempotencyLock(ctx context.Context, arg AcquireTrashIdempotencyLockParams) error {
	_, err := q.db.Exec(ctx, acquireTrashIdempotencyLock, arg.OwnerID, arg.IdempotencyKey)
	return err
}

const bumpPrivateMediaAccessVersion = `-- name: BumpPrivateMediaAccessVersion :exec
UPDATE mineg.media
SET access_version = access_version + 1
WHERE id = $1
`

func (q *Queries) BumpPrivateMediaAccessVersion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpPrivateMediaAccessVersion, id)
	return err
}

const createTrashRecord = `-- name: CreateTrashRecord :exec
INSERT INTO mineg.trash_records(media_id, owner_id, trashed_at)
VALUES ($1, $2, $3)
`

type CreateTrashRecordParams struct {
	MediaID   pgtype.UUID        `json:"media_id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	TrashedAt pgtype.Timestamptz `json:"trashed_at"`
}

func (q *Queries) CreateTrashRecord(ctx context.Context, arg CreateTrashRecordParams) error {
	_, err := q.db.Exec(ctx, createTrashRecord, arg.MediaID, arg.OwnerID, arg.TrashedAt)
	return err
}

const createTrashRequest = `-- name: CreateTrashRequest :exec
INSERT INTO mineg.trash_requests(
    owner_id, idempotency_key, media_id, request_hash, outcome, trashed_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTrashRequestParams struct {
	OwnerID        pgtype.UUID        `json:"owner_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	MediaID        pgtype.UUID        `json:"media_id"`
	RequestHash    []byte             `json:"request_hash"`
	Outcome        string             `json:"outcome"`
	TrashedAt      pgtype.Timestamptz `json:"trashed_at"`
}

func (q *Queries) CreateTrashRequest(ctx context.Context, arg CreateTrashRequestParams) error {
	_, err := q.db.Exec(ctx, createTrashRequest,
		arg.OwnerID,
		arg.IdempotencyKey,
		arg.MediaID,
		arg.RequestHash,
		arg.Outcome,
		arg.TrashedAt,
	)
	return err
}

const deactivateActiveShare = `-- name: DeactivateActiveShare :execrows
UPDATE mineg.shares
SET state = 'INACTIVE', version = version + 1, unshared_at = $2, updated_at = $2
WHERE media_id = $1 AND state = 'ACTIVE'
`

type DeactivateActiveShareParams struct {
	MediaID    pgtype.UUID        `json:"media_id"`
	UnsharedAt pgtype.Timestamptz `json:"unshared_at"`
}

func (q *Queries) DeactivateActiveShare(ctx context.Context, arg DeactivateActiveShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateActiveShare, arg.MediaID, arg.UnsharedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveTrashRecord = `-- name: FindActiveTrashRecord :one
SELECT media_id, owner_id, trashed_at, restored_at, purged_at FROM mineg.trash_records
WHERE media_id = $1
  AND owner_id = $2
  AND restored_at IS NULL
  AND purged_at IS NULL
`

type FindActiveTrashRecordParams struct {
	MediaID pgtype.UUID `json:"media_id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) FindActiveTrashRecord(ctx context.Context, arg FindActiveTrashRecordParams) (MinegTrashRecord, error) {
	row := q.db.QueryRow(ctx, findActiveTrashRecord, arg.MediaID, arg.OwnerID)
	var i MinegTrashRecord
	err := row.Scan(
		&i.MediaID,
		&i.OwnerID,
		&i.TrashedAt,
		&i.RestoredAt,
		&i.PurgedAt,
	)
	return i, err
}

const findPrivateMedia = `-- name: FindPrivateMedia :one
SELECT media.id,
       media.media_type,
       media.captured_at,
       media.created_at,
       media.width,
       media.height,
       media.duration_ms,
       COALESCE(originals.original_total_size, 0)::bigint AS original_total_size
FROM mineg.media AS media
LEFT JOIN mineg.trash_records AS trash
    ON trash.media_id = media.id
   AND trash.restored_at IS NULL
   AND trash.purged_at IS NULL
LEFT JOIN LATERAL (
    SELECT COALESCE(sum(resource.content_size), 0)::bigint AS original_total_size
    FROM mineg.media_resources AS resource
    WHERE resource.media_id = media.id
      AND resource.state = 'READY'
      AND resource.resource_type IN ('ORIGINAL', 'LIVE_PHOTO_VIDEO')
) AS originals ON TRUE
WHERE media.id = $1
  AND media.owner_id = $2
  AND media.upload_status = 'COMPLETED'
  AND trash.media_id IS NULL
`

type FindPrivateMediaParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

type FindPrivateMediaRow struct {
	ID                pgtype.UUID        `json:"id"`
	MediaType         string             `json:"media_type"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Width             pgtype.Int4        `json:"width"`
	Height            pgtype.Int4        `json:"height"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	OriginalTotalSize int64              `json:"original_total_size"`
}

func (q *Queries) FindPrivateMedia(ctx context.Context, arg FindPrivateMediaParams) (FindPrivateMediaRow, error) {
	row := q.db.QueryRow(ctx, findPrivateMedia, arg.ID, arg.OwnerID)
	var i FindPrivateMediaRow
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.OriginalTotalSize,
	)
	return i, err
}

const findTrashRequest = `-- name: FindTrashRequest :one
SELECT owner_id, idempotency_key, media_id, request_hash, outcome, trashed_at FROM mineg.trash_requests
WHERE owner_id = $1 AND idempotency_key = $2
`

type FindTrashRequestParams struct {
	OwnerID        pgtype.UUID `json:"owner_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) FindTrashRequest(ctx context.Context, arg FindTrashRequestParams) (MinegTrashRequest, error) {
	row := q.db.QueryRow(ctx, findTrashRequest, arg.OwnerID, arg.IdempotencyKey)
	var i MinegTrashRequest
	err := row.Scan(
		&i.OwnerID,
		&i.IdempotencyKey,
		&i.MediaID,
		&i.RequestHash,
		&i.Outcome,
		&i.TrashedAt,
	)
	return i, err
}

const listPrivateMedia = `-- name: ListPrivateMedia :many
SELECT media.id,
       media.media_type,
       media.captured_at,
       media.created_at,
       media.duration_ms,
       COALESCE(originals.original_total_size, 0)::bigint AS original_total_size
FROM mineg.media AS media
LEFT JOIN mineg.trash_records AS trash
    ON trash.media_id = media.id
   AND trash.restored_at IS NULL
   AND trash.purged_at IS NULL
LEFT JOIN LATERAL (
    SELECT COALESCE(sum(resource.content_size), 0)::bigint AS original_total_size
    FROM mineg.media_resources AS resource
    WHERE resource.media_id = media.id
      AND resource.state = 'READY'
      AND resource.resource_type IN ('ORIGINAL', 'LIVE_PHOTO_VIDEO')
) AS originals ON TRUE
WHERE media.owner_id = $1
  AND media.upload_status = 'COMPLETED'
  AND trash.media_id IS NULL
ORDER BY media.captured_at DESC, media.id DESC
LIMIT $2
`

type ListPrivateMediaParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
}

type ListPrivateMediaRow struct {
	ID                pgtype.UUID        `json:"id"`
	MediaType         string             `json:"media_type"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	OriginalTotalSize int64              `json:"original_total_size"`
}

func (q *Queries) ListPrivateMedia(ctx context.Context, arg ListPrivateMediaParams) ([]ListPrivateMediaRow, error) {
	rows, err := q.db.Query(ctx, listPrivateMedia, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrivateMediaRow
	for rows.Next() {
		var i ListPrivateMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.DurationMs,
			&i.OriginalTotalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivateMediaAccessResources = `-- name: ListPrivateMediaAccessResources :many
SELECT resource.id, resource.resource_type, resource.object_key, resource.mime_type, resource.content_size, resource.content_sha256
FROM mineg.media_resources AS resource
WHERE resource.media_id = $1
  AND resource.state = 'READY'
ORDER BY CASE resource.resource_type
    WHEN 'ORIGINAL' THEN 1
    WHEN 'LIVE_PHOTO_VIDEO' THEN 2
    WHEN 'THUMBNAIL' THEN 3
    WHEN 'VIDEO_COVER' THEN 4
    WHEN 'PREVIEW' THEN 5
    ELSE 6
END, resource.id
`

type ListPrivateMediaAccessResourcesRow struct {
	ID            pgtype.UUID `json:"id"`
	ResourceType  string      `json:"resource_type"`
	ObjectKey     string      `json:"object_key"`
	MimeType      string      `json:"mime_type"`
	ContentSize   int64       `json:"content_size"`
	ContentSha256 []byte      `json:"content_sha256"`
}

func (q *Queries) ListPrivateMediaAccessResources(ctx context.Context, mediaID pgtype.UUID) ([]ListPrivateMediaAccessResourcesRow, error) {
	rows, err := q.db.Query(ctx, listPrivateMediaAccessResources, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrivateMediaAccessResourcesRow
	for rows.Next() {
		var i ListPrivateMediaAccessResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.ObjectKey,
			&i.MimeType,
			&i.ContentSize,
			&i.ContentSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivateMediaAfter = `-- name: ListPrivateMediaAfter :many
SELECT media.id,
       media.media_type,
       media.captured_at,
       media.created_at,
       media.duration_ms,
       COALESCE(originals.original_total_size, 0)::bigint AS original_total_size
FROM mineg.media AS media
LEFT JOIN mineg.trash_records AS trash
    ON trash.media_id = media.id
   AND trash.restored_at IS NULL
   AND trash.purged_at IS NULL
LEFT JOIN LATERAL (
    SELECT COALESCE(sum(resource.content_size), 0)::bigint AS original_total_size
    FROM mineg.media_resources AS resource
    WHERE resource.media_id = media.id
      AND resource.state = 'READY'
      AND resource.resource_type IN ('ORIGINAL', 'LIVE_PHOTO_VIDEO')
) AS originals ON TRUE
WHERE media.owner_id = $1
  AND media.upload_status = 'COMPLETED'
  AND trash.media_id IS NULL
  AND (media.captured_at < $2 OR (media.captured_at = $2 AND media.id < $3))
ORDER BY media.captured_at DESC, media.id DESC
LIMIT $4
`

type ListPrivateMediaAfterParams struct {
	OwnerID    pgtype.UUID        `json:"owner_id"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	ID         pgtype.UUID        `json:"id"`
	Limit      int32              `json:"limit"`
}

type ListPrivateMediaAfterRow struct {
	ID                pgtype.UUID        `json:"id"`
	MediaType         string             `json:"media_type"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	OriginalTotalSize int64              `json:"original_total_size"`
}

func (q *Queries) ListPrivateMediaAfter(ctx context.Context, arg ListPrivateMediaAfterParams) ([]ListPrivateMediaAfterRow, error) {
	rows, err := q.db.Query(ctx, listPrivateMediaAfter,
		arg.OwnerID,
		arg.CapturedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrivateMediaAfterRow
	for rows.Next() {
		var i ListPrivateMediaAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.DurationMs,
			&i.OriginalTotalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivateMediaResources = `-- name: ListPrivateMediaResources :many
SELECT resource.id, resource.resource_type, resource.mime_type, resource.content_size, resource.content_sha256
FROM mineg.media_resources AS resource
JOIN mineg.media AS media ON media.id = resource.media_id
LEFT JOIN mineg.trash_records AS trash
    ON trash.media_id = media.id
   AND trash.restored_at IS NULL
   AND trash.purged_at IS NULL
WHERE resource.media_id = $1
  AND media.owner_id = $2
  AND media.upload_status = 'COMPLETED'
  AND resource.state = 'READY'
  AND trash.media_id IS NULL
ORDER BY CASE resource.resource_type
    WHEN 'ORIGINAL' THEN 1
    WHEN 'LIVE_PHOTO_VIDEO' THEN 2
    WHEN 'THUMBNAIL' THEN 3
    WHEN 'VIDEO_COVER' THEN 4
    WHEN 'PREVIEW' THEN 5
    ELSE 6
END, resource.id
`

type ListPrivateMediaResourcesParams struct {
	MediaID pgtype.UUID `json:"media_id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

type ListPrivateMediaResourcesRow struct {
	ID            pgtype.UUID `json:"id"`
	ResourceType  string      `json:"resource_type"`
	MimeType      string      `json:"mime_type"`
	ContentSize   int64       `json:"content_size"`
	ContentSha256 []byte      `json:"content_sha256"`
}

func (q *Queries) ListPrivateMediaResources(ctx context.Context, arg ListPrivateMediaResourcesParams) ([]ListPrivateMediaResourcesRow, error) {
	rows, err := q.db.Query(ctx, listPrivateMediaResources, arg.MediaID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrivateMediaResourcesRow
	for rows.Next() {
		var i ListPrivateMediaResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.MimeType,
			&i.ContentSize,
			&i.ContentSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPrivateMediaForAccess = `-- name: LockPrivateMediaForAccess :one
SELECT media.id, media.media_type, media.access_version
FROM mineg.media AS media
LEFT JOIN mineg.trash_records AS trash
    ON trash.media_id = media.id
   AND trash.restored_at IS NULL
   AND trash.purged_at IS NULL
WHERE media.id = $1
  AND media.owner_id = $2
  AND media.upload_status = 'COMPLETED'
  AND trash.media_id IS NULL
FOR UPDATE OF media
`

type LockPrivateMediaForAccessParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

type LockPrivateMediaForAccessRow struct {
	ID            pgtype.UUID `json:"id"`
	MediaType     string      `json:"media_type"`
	AccessVersion int64       `json:"access_version"`
}

func (q *Queries) LockPrivateMediaForAccess(ctx context.Context, arg LockPrivateMediaForAccessParams) (LockPrivateMediaForAccessRow, error) {
	row := q.db.QueryRow(ctx, lockPrivateMediaForAccess, arg.ID, arg.OwnerID)
	var i LockPrivateMediaForAccessRow
	err := row.Scan(&i.ID, &i.MediaType, &i.AccessVersion)
	return i, err
}

const lockPrivateMediaForTrash = `-- name: LockPrivateMediaForTrash :one
SELECT id
FROM mineg.media
WHERE id = $1
  AND owner_id = $2
  AND upload_status = 'COMPLETED'
FOR UPDATE
`

type LockPrivateMediaForTrashParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) LockPrivateMediaForTrash(ctx context.Context, arg LockPrivateMediaForTrashParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockPrivateMediaForTrash, arg.ID, arg.OwnerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
