// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: upload.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireUploadIdempotencyLock = `-- name: AcquireUploadIdempotencyLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':' || $2::text, 0))
`

type AcquireUploadIdempotencyLockParams struct {
	OwnerID        string `json:"owner_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) AcquireUploadIdempotencyLock(ctx context.Context, arg AcquireUploadIdempotencyLockParams) error {
	_, err := q.db.Exec(ctx, acquireUploadIdempotencyLock, arg.OwnerID, arg.IdempotencyKey)
	return err
}

const attachResourcesToMedia = `-- name: AttachResourcesToMedia :execrows
UPDATE mineg.media_resources
SET media_id = $2, state = 'READY'
WHERE upload_session_id = $1 AND state = 'PENDING'
`

type AttachResourcesToMediaParams struct {
	UploadSessionID pgtype.UUID `json:"upload_session_id"`
	MediaID         pgtype.UUID `json:"media_id"`
}

func (q *Queries) AttachResourcesToMedia(ctx context.Context, arg AttachResourcesToMediaParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachResourcesToMedia, arg.UploadSessionID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpUploadGrantGeneration = `-- name: BumpUploadGrantGeneration :one
UPDATE mineg.upload_sessions
SET grant_generation = grant_generation + 1, updated_at = $3
WHERE id = $1 AND owner_id = $2
RETURNING grant_generation
`

type BumpUploadGrantGenerationParams struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) BumpUploadGrantGeneration(ctx context.Context, arg BumpUploadGrantGenerationParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpUploadGrantGeneration, arg.ID, arg.OwnerID, arg.UpdatedAt)
	var grant_generation int32
	err := row.Scan(&grant_generation)
	return grant_generation, err
}

const completeUploadSession = `-- name: CompleteUploadSession :execrows
UPDATE mineg.upload_sessions
SET state = 'COMPLETED', media_id = $2, completed_at = $3, updated_at = $3
WHERE id = $1 AND state = 'VERIFYING'
`

type CompleteUploadSessionParams struct {
	ID          pgtype.UUID        `json:"id"`
	MediaID     pgtype.UUID        `json:"media_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeUploadSession, arg.ID, arg.MediaID, arg.CompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnreportedParts = `-- name: CountUnreportedParts :one
SELECT count(*) FROM mineg.upload_parts WHERE upload_session_id = $1 AND state <> 'UPLOADED'
`

func (q *Queries) CountUnreportedParts(ctx context.Context, uploadSessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreportedParts, uploadSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompletedOriginalMedia = `-- name: CreateCompletedOriginalMedia :one
INSERT INTO mineg.media(
    id, owner_id, source_upload_id, media_type, dedupe_fingerprint,
    content_revision, captured_at, content_sha256, mime_type, width, height, duration_ms, upload_status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $5, $8, $9, $10, $11, 'COMPLETED')
ON CONFLICT (owner_id, dedupe_fingerprint, content_revision) DO NOTHING
RETURNING id, owner_id, source_upload_id, media_type, dedupe_fingerprint, content_revision, captured_at, upload_status, created_at, content_sha256, mime_type, width, height, duration_ms, access_version
`

type CreateCompletedOriginalMediaParams struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	SourceUploadID    pgtype.UUID        `json:"source_upload_id"`
	MediaType         string             `json:"media_type"`
	DedupeFingerprint []byte             `json:"dedupe_fingerprint"`
	ContentRevision   int32              `json:"content_revision"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
	MimeType          string             `json:"mime_type"`
	Width             pgtype.Int4        `json:"width"`
	Height            pgtype.Int4        `json:"height"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
}

func (q *Queries) CreateCompletedOriginalMedia(ctx context.Context, arg CreateCompletedOriginalMediaParams) (MinegMedium, error) {
	row := q.db.QueryRow(ctx, createCompletedOriginalMedia,
		arg.ID,
		arg.OwnerID,
		arg.SourceUploadID,
		arg.MediaType,
		arg.DedupeFingerprint,
		arg.ContentRevision,
		arg.CapturedAt,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.DurationMs,
	)
	var i MinegMedium
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceUploadID,
		&i.MediaType,
		&i.DedupeFingerprint,
		&i.ContentRevision,
		&i.CapturedAt,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.ContentSha256,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.AccessVersion,
	)
	return i, err
}

const createDeduplicatedOriginalUploadSession = `-- name: CreateDeduplicatedOriginalUploadSession :one
INSERT INTO mineg.upload_sessions(
    id, owner_id, idempotency_key, request_hash, purpose, state, dedupe_fingerprint,
    content_revision, client_media_id, media_type, captured_at, content_sha256, mime_type,
    width, height, duration_ms, media_id, expires_at, completed_at
) VALUES ($1, $2, $3, $4, 'MEDIA_ORIGINAL', 'COMPLETED', $5, $6, $7, $8, $9, $5, $10,
          $11, $12, $13, $14, $15, $16)
RETURNING id, owner_id, idempotency_key, request_hash, purpose, state, dedupe_fingerprint, content_revision, client_media_id, media_type, captured_at, media_id, expires_at, completed_at, created_at, updated_at, content_sha256, mime_type, grant_generation, width, height, duration_ms
`

type CreateDeduplicatedOriginalUploadSessionParams struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       []byte             `json:"request_hash"`
	DedupeFingerprint []byte             `json:"dedupe_fingerprint"`
	ContentRevision   int32              `json:"content_revision"`
	ClientMediaID     pgtype.UUID        `json:"client_media_id"`
	MediaType         string             `json:"media_type"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
	MimeType          string             `json:"mime_type"`
	Width             pgtype.Int4        `json:"width"`
	Height            pgtype.Int4        `json:"height"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	MediaID           pgtype.UUID        `json:"media_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateDeduplicatedOriginalUploadSession(ctx context.Context, arg CreateDeduplicatedOriginalUploadSessionParams) (MinegUploadSession, error) {
	row := q.db.QueryRow(ctx, createDeduplicatedOriginalUploadSession,
		arg.ID,
		arg.OwnerID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.DedupeFingerprint,
		arg.ContentRevision,
		arg.ClientMediaID,
		arg.MediaType,
		arg.CapturedAt,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.MediaID,
		arg.ExpiresAt,
		arg.CompletedAt,
	)
	var i MinegUploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Purpose,
		&i.State,
		&i.DedupeFingerprint,
		&i.ContentRevision,
		&i.ClientMediaID,
		&i.MediaType,
		&i.CapturedAt,
		&i.MediaID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentSha256,
		&i.MimeType,
		&i.GrantGeneration,
		&i.Width,
		&i.Height,
		&i.DurationMs,
	)
	return i, err
}

const createExpectedUploadPart = `-- name: CreateExpectedUploadPart :exec
INSERT INTO mineg.upload_parts(
    upload_session_id, resource_id, part_number, expected_size, expected_sha256
) VALUES ($1, $2, $3, $4, $5)
`

type CreateExpectedUploadPartParams struct {
	UploadSessionID pgtype.UUID `json:"upload_session_id"`
	ResourceID      pgtype.UUID `json:"resource_id"`
	PartNumber      int32       `json:"part_number"`
	ExpectedSize    int64       `json:"expected_size"`
	ExpectedSha256  []byte      `json:"expected_sha256"`
}

func (q *Queries) CreateExpectedUploadPart(ctx context.Context, arg CreateExpectedUploadPartParams) error {
	_, err := q.db.Exec(ctx, createExpectedUploadPart,
		arg.UploadSessionID,
		arg.ResourceID,
		arg.PartNumber,
		arg.ExpectedSize,
		arg.ExpectedSha256,
	)
	return err
}

const createOriginalUploadResource = `-- name: CreateOriginalUploadResource :exec
INSERT INTO mineg.media_resources(
    id, upload_session_id, resource_type, object_key, multipart_upload_id,
    content_size, content_sha256, mime_type, part_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOriginalUploadResourceParams struct {
	ID                pgtype.UUID `json:"id"`
	UploadSessionID   pgtype.UUID `json:"upload_session_id"`
	ResourceType      string      `json:"resource_type"`
	ObjectKey         string      `json:"object_key"`
	MultipartUploadID string      `json:"multipart_upload_id"`
	ContentSize       int64       `json:"content_size"`
	ContentSha256     []byte      `json:"content_sha256"`
	MimeType          string      `json:"mime_type"`
	PartCount         int32       `json:"part_count"`
}

func (q *Queries) CreateOriginalUploadResource(ctx context.Context, arg CreateOriginalUploadResourceParams) error {
	_, err := q.db.Exec(ctx, createOriginalUploadResource,
		arg.ID,
		arg.UploadSessionID,
		arg.ResourceType,
		arg.ObjectKey,
		arg.MultipartUploadID,
		arg.ContentSize,
		arg.ContentSha256,
		arg.MimeType,
		arg.PartCount,
	)
	return err
}

const createOriginalUploadSession = `-- name: CreateOriginalUploadSession :one
INSERT INTO mineg.upload_sessions(
    id, owner_id, idempotency_key, request_hash, purpose, dedupe_fingerprint,
    content_revision, client_media_id, media_type, captured_at, content_sha256, mime_type,
    width, height, duration_ms, expires_at
) VALUES ($1, $2, $3, $4, 'MEDIA_ORIGINAL', $5, $6, $7, $8, $9, $5, $10, $11, $12, $13, $14)
RETURNING id, owner_id, idempotency_key, request_hash, purpose, state, dedupe_fingerprint, content_revision, client_media_id, media_type, captured_at, media_id, expires_at, completed_at, created_at, updated_at, content_sha256, mime_type, grant_generation, width, height, duration_ms
`

type CreateOriginalUploadSessionParams struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestHash       []byte             `json:"request_hash"`
	DedupeFingerprint []byte             `json:"dedupe_fingerprint"`
	ContentRevision   int32              `json:"content_revision"`
	ClientMediaID     pgtype.UUID        `json:"client_media_id"`
	MediaType         string             `json:"media_type"`
	CapturedAt        pgtype.Timestamptz `json:"captured_at"`
	MimeType          string             `json:"mime_type"`
	Width             pgtype.Int4        `json:"width"`
	Height            pgtype.Int4        `json:"height"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOriginalUploadSession(ctx context.Context, arg CreateOriginalUploadSessionParams) (MinegUploadSession, error) {
	row := q.db.QueryRow(ctx, createOriginalUploadSession,
		arg.ID,
		arg.OwnerID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.DedupeFingerprint,
		arg.ContentRevision,
		arg.ClientMediaID,
		arg.MediaType,
		arg.CapturedAt,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.ExpiresAt,
	)
	var i MinegUploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Purpose,
		&i.State,
		&i.DedupeFingerprint,
		&i.ContentRevision,
		&i.ClientMediaID,
		&i.MediaType,
		&i.CapturedAt,
		&i.MediaID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentSha256,
		&i.MimeType,
		&i.GrantGeneration,
		&i.Width,
		&i.Height,
		&i.DurationMs,
	)
	return i, err
}

const ensureClientAlbum = `-- name: EnsureClientAlbum :one
INSERT INTO mineg.albums(owner_id, kind, client_album_id, device_installation_id, display_name)
VALUES ($1, 'CLIENT', $2, $3, $4)
ON CONFLICT (owner_id, device_installation_id, client_album_id) WHERE kind = 'CLIENT'
DO UPDATE SET display_name = EXCLUDED.display_name
RETURNING id, owner_id, kind, client_album_id, created_at, device_installation_id, display_name
`

type EnsureClientAlbumParams struct {
	OwnerID              pgtype.UUID `json:"owner_id"`
	ClientAlbumID        pgtype.Text `json:"client_album_id"`
	DeviceInstallationID pgtype.Text `json:"device_installation_id"`
	DisplayName          pgtype.Text `json:"display_name"`
}

func (q *Queries) EnsureClientAlbum(ctx context.Context, arg EnsureClientAlbumParams) (MinegAlbum, error) {
	row := q.db.QueryRow(ctx, ensureClientAlbum,
		arg.OwnerID,
		arg.ClientAlbumID,
		arg.DeviceInstallationID,
		arg.DisplayName,
	)
	var i MinegAlbum
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.ClientAlbumID,
		&i.CreatedAt,
		&i.DeviceInstallationID,
		&i.DisplayName,
	)
	return i, err
}

const ensureLibraryAlbum = `-- name: EnsureLibraryAlbum :one
INSERT INTO mineg.albums(owner_id, kind)
VALUES ($1, 'LIBRARY')
ON CONFLICT (owner_id) WHERE kind = 'LIBRARY' DO UPDATE SET owner_id = EXCLUDED.owner_id
RETURNING id, owner_id, kind, client_album_id, created_at, device_installation_id, display_name
`

func (q *Queries) EnsureLibraryAlbum(ctx context.Context, ownerID pgtype.UUID) (MinegAlbum, error) {
	row := q.db.QueryRow(ctx, ensureLibraryAlbum, ownerID)
	var i MinegAlbum
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.ClientAlbumID,
		&i.CreatedAt,
		&i.DeviceInstallationID,
		&i.DisplayName,
	)
	return i, err
}

const expireUploadSession = `-- name: ExpireUploadSession :execrows
UPDATE mineg.upload_sessions
SET state = 'EXPIRED', updated_at = $3
WHERE id = $1 AND owner_id = $2 AND state IN ('PENDING', 'VERIFYING') AND expires_at <= $3
`

type ExpireUploadSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ExpireUploadSession(ctx context.Context, arg ExpireUploadSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireUploadSession, arg.ID, arg.OwnerID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireUploadSessions = `-- name: ExpireUploadSessions :execrows
UPDATE mineg.upload_sessions
SET state = 'EXPIRED', updated_at = $1
WHERE state IN ('PENDING', 'VERIFYING') AND expires_at <= $1
`

func (q *Queries) ExpireUploadSessions(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expireUploadSessions, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findCompletedMediaByFingerprint = `-- name: FindCompletedMediaByFingerprint :one
SELECT id, owner_id, source_upload_id, media_type, dedupe_fingerprint, content_revision, captured_at, upload_status, created_at, content_sha256, mime_type, width, height, duration_ms, access_version FROM mineg.media
WHERE owner_id = $1 AND dedupe_fingerprint = $2 AND content_revision = $3
  AND upload_status = 'COMPLETED'
`

type FindCompletedMediaByFingerprintParams struct {
	OwnerID           pgtype.UUID `json:"owner_id"`
	DedupeFingerprint []byte      `json:"dedupe_fingerprint"`
	ContentRevision   int32       `json:"content_revision"`
}

func (q *Queries) FindCompletedMediaByFingerprint(ctx context.Context, arg FindCompletedMediaByFingerprintParams) (MinegMedium, error) {
	row := q.db.QueryRow(ctx, findCompletedMediaByFingerprint, arg.OwnerID, arg.DedupeFingerprint, arg.ContentRevision)
	var i MinegMedium
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceUploadID,
		&i.MediaType,
		&i.DedupeFingerprint,
		&i.ContentRevision,
		&i.CapturedAt,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.ContentSha256,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.AccessVersion,
	)
	return i, err
}

const findUploadByIdempotency = `-- name: FindUploadByIdempotency :one
SELECT id, owner_id, idempotency_key, request_hash, purpose, state, dedupe_fingerprint, content_revision, client_media_id, media_type, captured_at, media_id, expires_at, completed_at, created_at, updated_at, content_sha256, mime_type, grant_generation, width, height, duration_ms FROM mineg.upload_sessions
WHERE owner_id = $1 AND idempotency_key = $2
`

type FindUploadByIdempotencyParams struct {
	OwnerID        pgtype.UUID `json:"owner_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) FindUploadByIdempotency(ctx context.Context, arg FindUploadByIdempotencyParams) (MinegUploadSession, error) {
	row := q.db.QueryRow(ctx, findUploadByIdempotency, arg.OwnerID, arg.IdempotencyKey)
	var i MinegUploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Purpose,
		&i.State,
		&i.DedupeFingerprint,
		&i.ContentRevision,
		&i.ClientMediaID,
		&i.MediaType,
		&i.CapturedAt,
		&i.MediaID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentSha256,
		&i.MimeType,
		&i.GrantGeneration,
		&i.Width,
		&i.Height,
		&i.DurationMs,
	)
	return i, err
}

const findUploadForOwner = `-- name: FindUploadForOwner :one
SELECT id, owner_id, idempotency_key, request_hash, purpose, state, dedupe_fingerprint, content_revision, client_media_id, media_type, captured_at, media_id, expires_at, completed_at, created_at, updated_at, content_sha256, mime_type, grant_generation, width, height, duration_ms FROM mineg.upload_sessions WHERE id = $1 AND owner_id = $2
`

type FindUploadForOwnerParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) FindUploadForOwner(ctx context.Context, arg FindUploadForOwnerParams) (MinegUploadSession, error) {
	row := q.db.QueryRow(ctx, findUploadForOwner, arg.ID, arg.OwnerID)
	var i MinegUploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Purpose,
		&i.State,
		&i.DedupeFingerprint,
		&i.ContentRevision,
		&i.ClientMediaID,
		&i.MediaType,
		&i.CapturedAt,
		&i.MediaID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentSha256,
		&i.MimeType,
		&i.GrantGeneration,
		&i.Width,
		&i.Height,
		&i.DurationMs,
	)
	return i, err
}

const findUploadPartForUpdate = `-- name: FindUploadPartForUpdate :one
SELECT part.upload_session_id, part.resource_id, part.part_number, part.expected_size, part.expected_sha256, part.etag, part.reported_size, part.reported_sha256, part.state, part.reported_at, resource.object_key, resource.multipart_upload_id, resource.resource_type
FROM mineg.upload_parts part
JOIN mineg.media_resources resource ON resource.id = part.resource_id
WHERE part.upload_session_id = $1 AND part.resource_id = $2 AND part.part_number = $3
FOR UPDATE OF part
`

type FindUploadPartForUpdateParams struct {
	UploadSessionID pgtype.UUID `json:"upload_session_id"`
	ResourceID      pgtype.UUID `json:"resource_id"`
	PartNumber      int32       `json:"part_number"`
}

type FindUploadPartForUpdateRow struct {
	UploadSessionID   pgtype.UUID        `json:"upload_session_id"`
	ResourceID        pgtype.UUID        `json:"resource_id"`
	PartNumber        int32              `json:"part_number"`
	ExpectedSize      int64              `json:"expected_size"`
	ExpectedSha256    []byte             `json:"expected_sha256"`
	Etag              pgtype.Text        `json:"etag"`
	ReportedSize      pgtype.Int8        `json:"reported_size"`
	ReportedSha256    []byte             `json:"reported_sha256"`
	State             string             `json:"state"`
	ReportedAt        pgtype.Timestamptz `json:"reported_at"`
	ObjectKey         string             `json:"object_key"`
	MultipartUploadID string             `json:"multipart_upload_id"`
	ResourceType      string             `json:"resource_type"`
}

func (q *Queries) FindUploadPartForUpdate(ctx context.Context, arg FindUploadPartForUpdateParams) (FindUploadPartForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findUploadPartForUpdate, arg.UploadSessionID, arg.ResourceID, arg.PartNumber)
	var i FindUploadPartForUpdateRow
	err := row.Scan(
		&i.UploadSessionID,
		&i.ResourceID,
		&i.PartNumber,
		&i.ExpectedSize,
		&i.ExpectedSha256,
		&i.Etag,
		&i.ReportedSize,
		&i.ReportedSha256,
		&i.State,
		&i.ReportedAt,
		&i.ObjectKey,
		&i.MultipartUploadID,
		&i.ResourceType,
	)
	return i, err
}

const linkMediaToAlbum = `-- name: LinkMediaToAlbum :exec
INSERT INTO mineg.media_album_links(media_id, album_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkMediaToAlbumParams struct {
	MediaID pgtype.UUID `json:"media_id"`
	AlbumID pgtype.UUID `json:"album_id"`
}

func (q *Queries) LinkMediaToAlbum(ctx context.Context, arg LinkMediaToAlbumParams) error {
	_, err := q.db.Exec(ctx, linkMediaToAlbum, arg.MediaID, arg.AlbumID)
	return err
}

const linkUploadSessionAlbumsToMedia = `-- name: LinkUploadSessionAlbumsToMedia :exec
INSERT INTO mineg.media_album_links(media_id, album_id)
SELECT $2, album_id FROM mineg.upload_session_client_albums
WHERE upload_session_id = $1
ON CONFLICT DO NOTHING
`

type LinkUploadSessionAlbumsToMediaParams struct {
	UploadSessionID pgtype.UUID `json:"upload_session_id"`
	MediaID         pgtype.UUID `json:"media_id"`
}

func (q *Queries) LinkUploadSessionAlbumsToMedia(ctx context.Context, arg LinkUploadSessionAlbumsToMediaParams) error {
	_, err := q.db.Exec(ctx, linkUploadSessionAlbumsToMedia, arg.UploadSessionID, arg.MediaID)
	return err
}

const linkUploadSessionToClientAlbum = `-- name: LinkUploadSessionToClientAlbum :exec
INSERT INTO mineg.upload_session_client_albums(upload_session_id, album_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkUploadSessionToClientAlbumParams struct {
	UploadSessionID pgtype.UUID `json:"upload_session_id"`
	AlbumID         pgtype.UUID `json:"album_id"`
}

func (q *Queries) LinkUploadSessionToClientAlbum(ctx context.Context, arg LinkUploadSessionToClientAlbumParams) error {
	_, err := q.db.Exec(ctx, linkUploadSessionToClientAlbum, arg.UploadSessionID, arg.AlbumID)
	return err
}

const listOwnerMedia = `-- name: ListOwnerMedia :many
SELECT id, media_type, content_revision, captured_at, created_at
FROM mineg.media
WHERE owner_id = $1 AND upload_status = 'COMPLETED'
ORDER BY captured_at DESC, id DESC
LIMIT $2
`

type ListOwnerMediaParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
}

type ListOwnerMediaRow struct {
	ID              pgtype.UUID        `json:"id"`
	MediaType       string             `json:"media_type"`
	ContentRevision int32              `json:"content_revision"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOwnerMedia(ctx context.Context, arg ListOwnerMediaParams) ([]ListOwnerMediaRow, error) {
	rows, err := q.db.Query(ctx, listOwnerMedia, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerMediaRow
	for rows.Next() {
		var i ListOwnerMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.ContentRevision,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerMediaAfter = `-- name: ListOwnerMediaAfter :many
SELECT id, media_type, content_revision, captured_at, created_at
FROM mineg.media
WHERE owner_id = $1
  AND upload_status = 'COMPLETED'
  AND (captured_at < $2 OR (captured_at = $2 AND id < $3))
ORDER BY captured_at DESC, id DESC
LIMIT $4
`

type ListOwnerMediaAfterParams struct {
	OwnerID    pgtype.UUID        `json:"owner_id"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	ID         pgtype.UUID        `json:"id"`
	Limit      int32              `json:"limit"`
}

type ListOwnerMediaAfterRow struct {
	ID              pgtype.UUID        `json:"id"`
	MediaType       string             `json:"media_type"`
	ContentRevision int32              `json:"content_revision"`
	CapturedAt      pgtype.Timestamptz `json:"captured_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOwnerMediaAfter(ctx context.Context, arg ListOwnerMediaAfterParams) ([]ListOwnerMediaAfterRow, error) {
	rows, err := q.db.Query(ctx, listOwnerMediaAfter,
		arg.OwnerID,
		arg.CapturedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerMediaAfterRow
	for rows.Next() {
		var i ListOwnerMediaAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.ContentRevision,
			&i.CapturedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadParts = `-- name: ListUploadParts :many
SELECT upload_session_id, resource_id, part_number, expected_size, expected_sha256, etag, reported_size, reported_sha256, state, reported_at FROM mineg.upload_parts WHERE upload_session_id = $1 ORDER BY resource_id, part_number
`

func (q *Queries) ListUploadParts(ctx context.Context, uploadSessionID pgtype.UUID) ([]MinegUploadPart, error) {
	rows, err := q.db.Query(ctx, listUploadParts, uploadSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MinegUploadPart
	for rows.Next() {
		var i MinegUploadPart
		if err := rows.Scan(
			&i.UploadSessionID,
			&i.ResourceID,
			&i.PartNumber,
			&i.ExpectedSize,
			&i.ExpectedSha256,
			&i.Etag,
			&i.ReportedSize,
			&i.ReportedSha256,
			&i.State,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadResources = `-- name: ListUploadResources :many
SELECT id, upload_session_id, media_id, resource_type, object_key, multipart_upload_id, part_count, state, created_at, content_size, content_sha256, mime_type FROM mineg.media_resources WHERE upload_session_id = $1 ORDER BY resource_type, id
`

func (q *Queries) ListUploadResources(ctx context.Context, uploadSessionID pgtype.UUID) ([]MinegMediaResource, error) {
	rows, err := q.db.Query(ctx, listUploadResources, uploadSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MinegMediaResource
	for rows.Next() {
		var i MinegMediaResource
		if err := rows.Scan(
			&i.ID,
			&i.UploadSessionID,
			&i.MediaID,
			&i.ResourceType,
			&i.ObjectKey,
			&i.MultipartUploadID,
			&i.PartCount,
			&i.State,
			&i.CreatedAt,
			&i.ContentSize,
			&i.ContentSha256,
			&i.MimeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUploadForCompletion = `-- name: LockUploadForCompletion :one
SELECT id, owner_id, idempotency_key, request_hash, purpose, state, dedupe_fingerprint, content_revision, client_media_id, media_type, captured_at, media_id, expires_at, completed_at, created_at, updated_at, content_sha256, mime_type, grant_generation, width, height, duration_ms FROM mineg.upload_sessions
WHERE id = $1 AND owner_id = $2
FOR UPDATE
`

type LockUploadForCompletionParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) LockUploadForCompletion(ctx context.Context, arg LockUploadForCompletionParams) (MinegUploadSession, error) {
	row := q.db.QueryRow(ctx, lockUploadForCompletion, arg.ID, arg.OwnerID)
	var i MinegUploadSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Purpose,
		&i.State,
		&i.DedupeFingerprint,
		&i.ContentRevision,
		&i.ClientMediaID,
		&i.MediaType,
		&i.CapturedAt,
		&i.MediaID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentSha256,
		&i.MimeType,
		&i.GrantGeneration,
		&i.Width,
		&i.Height,
		&i.DurationMs,
	)
	return i, err
}

const markUploadInvalid = `-- name: MarkUploadInvalid :exec
UPDATE mineg.upload_sessions
SET state = 'INVALID', updated_at = $2
WHERE id = $1 AND state IN ('PENDING', 'VERIFYING')
`

type MarkUploadInvalidParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkUploadInvalid(ctx context.Context, arg MarkUploadInvalidParams) error {
	_, err := q.db.Exec(ctx, markUploadInvalid, arg.ID, arg.UpdatedAt)
	return err
}

const markUploadPartsVerified = `-- name: MarkUploadPartsVerified :exec
UPDATE mineg.upload_parts SET state = 'VERIFIED'
WHERE upload_session_id = $1 AND state = 'UPLOADED'
`

func (q *Queries) MarkUploadPartsVerified(ctx context.Context, uploadSessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUploadPartsVerified, uploadSessionID)
	return err
}

const markUploadResourcesInvalid = `-- name: MarkUploadResourcesInvalid :exec
UPDATE mineg.media_resources SET state = 'INVALID'
WHERE upload_session_id = $1 AND state = 'PENDING'
`

func (q *Queries) MarkUploadResourcesInvalid(ctx context.Context, uploadSessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUploadResourcesInvalid, uploadSessionID)
	return err
}

const markUploadVerifying = `-- name: MarkUploadVerifying :execrows
UPDATE mineg.upload_sessions
SET state = 'VERIFYING', updated_at = $3
WHERE id = $1 AND owner_id = $2 AND state = 'PENDING' AND expires_at > $3
`

type MarkUploadVerifyingParams struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkUploadVerifying(ctx context.Context, arg MarkUploadVerifyingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadVerifying, arg.ID, arg.OwnerID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reportUploadPart = `-- name: ReportUploadPart :execrows
UPDATE mineg.upload_parts
SET etag = $4, reported_size = $5, reported_sha256 = $6, state = 'UPLOADED', reported_at = $7
WHERE upload_session_id = $1 AND resource_id = $2 AND part_number = $3
  AND expected_size = $5 AND expected_sha256 = $6
  AND (state = 'PENDING' OR (etag = $4 AND reported_size = $5 AND reported_sha256 = $6))
`

type ReportUploadPartParams struct {
	UploadSessionID pgtype.UUID        `json:"upload_session_id"`
	ResourceID      pgtype.UUID        `json:"resource_id"`
	PartNumber      int32              `json:"part_number"`
	Etag            pgtype.Text        `json:"etag"`
	ReportedSize    pgtype.Int8        `json:"reported_size"`
	ReportedSha256  []byte             `json:"reported_sha256"`
	ReportedAt      pgtype.Timestamptz `json:"reported_at"`
}

func (q *Queries) ReportUploadPart(ctx context.Context, arg ReportUploadPartParams) (int64, error) {
	result, err := q.db.Exec(ctx, reportUploadPart,
		arg.UploadSessionID,
		arg.ResourceID,
		arg.PartNumber,
		arg.Etag,
		arg.ReportedSize,
		arg.ReportedSha256,
		arg.ReportedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetUploadParts = `-- name: ResetUploadParts :exec
UPDATE mineg.upload_parts
SET etag = NULL, reported_size = NULL, reported_sha256 = NULL, state = 'PENDING', reported_at = NULL
WHERE upload_session_id = $1
`

func (q *Queries) ResetUploadParts(ctx context.Context, uploadSessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetUploadParts, uploadSessionID)
	return err
}

const resetUploadPending = `-- name: ResetUploadPending :execrows
UPDATE mineg.upload_sessions
SET state = 'PENDING', updated_at = $2
WHERE id = $1 AND state = 'VERIFYING'
`

type ResetUploadPendingParams struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResetUploadPending(ctx context.Context, arg ResetUploadPendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetUploadPending, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviveExpiredUploadSession = `-- name: ReviveExpiredUploadSession :execrows
UPDATE mineg.upload_sessions
SET state = 'PENDING', expires_at = $3, updated_at = $4
WHERE id = $1 AND owner_id = $2 AND state = 'EXPIRED'
`

type ReviveExpiredUploadSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReviveExpiredUploadSession(ctx context.Context, arg ReviveExpiredUploadSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviveExpiredUploadSession,
		arg.ID,
		arg.OwnerID,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviveUploadResource = `-- name: ReviveUploadResource :execrows
UPDATE mineg.media_resources
SET multipart_upload_id = $3, media_id = NULL, state = 'PENDING'
WHERE id = $1 AND upload_session_id = $2 AND state = 'INVALID'
`

type ReviveUploadResourceParams struct {
	ID                pgtype.UUID `json:"id"`
	UploadSessionID   pgtype.UUID `json:"upload_session_id"`
	MultipartUploadID string      `json:"multipart_upload_id"`
}

func (q *Queries) ReviveUploadResource(ctx context.Context, arg ReviveUploadResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviveUploadResource, arg.ID, arg.UploadSessionID, arg.MultipartUploadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
