/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unauthenticated integration probe; not a business API. */
        get: operations["runPlatformProbe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/approval-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApprovalStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v1/me/avatar/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAvatarUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/avatar/uploads/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeAvatarUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvatarReadGrant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMediaUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportMediaUploadPart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompletedOwnerMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/private/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPrivateMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/private/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrivateMediaDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/private/media/{media_id}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPrivateMediaAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/private/media/{media_id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trashPrivateMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/private/media/{media_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setPrivateMediaShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFamilyMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFamilyMediaDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/media/{media_id}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFamilyMediaAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTrashMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/{media_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreTrashMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/help/faq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFAQ"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["restoreAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminSignOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/approvals/{approval_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
        };
        PlatformProbe: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            api_version: "v1";
            /** Format: date-time */
            server_time: string;
        };
        SignUpRequest: {
            phone: string;
            password: string;
            device_installation_id: string;
            /** @enum {string} */
            platform: "ANDROID" | "IOS" | "HARMONYOS";
        };
        SignUpResult: {
            /** Format: uuid */
            user_id: string;
            access_token: string;
            /** Format: date-time */
            access_expires_at: string;
            refresh_token: string;
            /** Format: date-time */
            refresh_expires_at: string;
            approval_status: components["schemas"]["ApprovalStatusValue"];
            next_step: components["schemas"]["NextStep"];
        };
        SignInRequest: {
            phone: string;
            password: string;
            device_installation_id: string;
            /** @enum {string} */
            platform: "ANDROID" | "IOS" | "HARMONYOS";
            /** @enum {boolean} */
            agreement_accepted: true;
            terms_version: string;
            privacy_version: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenResult: {
            /** Format: uuid */
            user_id: string;
            access_token: string;
            /** Format: date-time */
            access_expires_at: string;
            refresh_token: string;
            /** Format: date-time */
            refresh_expires_at: string;
            approval_status: components["schemas"]["ApprovalStatusValue"];
            next_step: components["schemas"]["NextStep"];
        };
        ApprovalStatus: {
            status: components["schemas"]["ApprovalStatusValue"];
            next_step: components["schemas"]["NextStep"];
        };
        /** @enum {string} */
        ApprovalStatusValue: "PENDING" | "APPROVED";
        /** @enum {string} */
        NextStep: "REVIEW_PENDING" | "APP_HOME";
        Profile: {
            /** Format: uuid */
            id: string;
            nickname: string;
            masked_phone: string;
            /** Format: uri */
            avatar_url?: string;
            version: number;
        };
        UpdateProfileRequest: {
            nickname: string;
        };
        CreateAvatarUploadRequest: {
            /** @enum {string} */
            content_type: "image/jpeg" | "image/png" | "image/heic" | "image/heif" | "image/webp";
            source_size: number;
            display_size: number;
            width: number;
            height: number;
            /** @description Unpadded standard base64 SHA-256 digest. */
            content_sha256: string;
        };
        ObjectGrant: {
            /** Format: uri */
            url: string;
            /** @enum {string} */
            method: "GET" | "PUT";
            /** Format: date-time */
            expires_at: string;
            headers: {
                [key: string]: string;
            };
        };
        AvatarUploadResult: {
            /** Format: uuid */
            upload_id: string;
            grant: components["schemas"]["ObjectGrant"];
        };
        /** @enum {string} */
        MediaType: "PHOTO" | "VIDEO" | "GIF" | "LIVE_PHOTO" | "DYNAMIC";
        /** @enum {string} */
        MediaResourceType: "ORIGINAL" | "THUMBNAIL" | "VIDEO_COVER" | "PREVIEW" | "LIVE_PHOTO_VIDEO" | "DYNAMIC_PREVIEW";
        MediaPartPlan: {
            part_number: number;
            content_size: number;
            /** @description Unpadded standard base64 SHA-256 of this original-media block. */
            content_sha256: string;
        };
        MediaResourcePlan: {
            /** Format: uuid */
            resource_id: string;
            resource_type: components["schemas"]["MediaResourceType"];
            /** @description Required per resource by stage05-v1; inherited from the top-level MIME for older protocols. */
            mime_type?: string;
            content_size: number;
            /** @description Unpadded standard base64 whole original-media digest. */
            content_sha256: string;
            parts: components["schemas"]["MediaPartPlan"][];
        };
        CreateMediaUploadRequest: {
            /** @enum {string} */
            protocol_version: "stage03-v2" | "stage04-v1" | "stage05-v1";
            /**
             * Format: uuid
             * @description Stable client-generated media ID.
             */
            client_media_id: string;
            /** @description Unpadded standard base64 SHA-256 of the original media bytes. */
            content_sha256: string;
            content_revision: number;
            media_type: components["schemas"]["MediaType"];
            /** Format: date-time */
            captured_at: string;
            mime_type: string;
            width?: number;
            height?: number;
            duration_ms?: number;
            resources: components["schemas"]["MediaResourcePlan"][];
            /** @description Required for stage04-v1 when client album membership is supplied. */
            device_installation_id?: string;
            client_albums?: components["schemas"]["ClientAlbumRef"][];
        };
        ClientAlbumRef: {
            client_album_id: string;
            name: string;
        };
        MediaPartGrant: {
            part_number: number;
            grant: components["schemas"]["ObjectGrant"];
        };
        MediaResourceGrant: {
            /** Format: uuid */
            resource_id: string;
            object_key: string;
            upload_id: string;
            parts: components["schemas"]["MediaPartGrant"][];
        };
        MediaUploadGrant: {
            /** @enum {string} */
            purpose: "MEDIA_ORIGINAL";
            scope_prefix: string;
            /** Format: date-time */
            expires_at: string;
            resources: components["schemas"]["MediaResourceGrant"][];
        };
        MediaResourceStatus: {
            /** Format: uuid */
            resource_id: string;
            resource_type: components["schemas"]["MediaResourceType"];
            object_key?: string;
            content_size?: number;
            part_count: number;
            uploaded_parts: number;
            /** @description Exact server-confirmed multipart part numbers for safe client recovery. */
            confirmed_part_numbers: number[];
        };
        MediaUploadSession: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            client_media_id: string;
            /** @enum {string} */
            state: "PENDING" | "VERIFYING" | "COMPLETED" | "EXPIRED" | "INVALID";
            /** @enum {string} */
            purpose: "MEDIA_ORIGINAL";
            /** Format: uuid */
            media_id?: string;
            deduplicated: boolean;
            grant_generation: number;
            /** Format: date-time */
            expires_at: string;
            grant?: components["schemas"]["MediaUploadGrant"];
            resources: components["schemas"]["MediaResourceStatus"][];
        };
        ReportMediaPartRequest: {
            /** Format: uuid */
            resource_id: string;
            part_number: number;
            content_size: number;
            content_sha256: string;
            etag: string;
        };
        MediaPartResult: {
            /** Format: uuid */
            upload_id: string;
            /** Format: uuid */
            resource_id: string;
            part_number: number;
            /** @enum {string} */
            state: "UPLOADED";
        };
        CompleteMediaUploadRequest: Record<string, never>;
        CompleteMediaUploadResult: {
            /** Format: uuid */
            upload_id: string;
            /** Format: uuid */
            media_id: string;
            /** @enum {string} */
            state: "COMPLETED";
            /** @enum {string} */
            outcome: "COMPLETED" | "ALREADY_COMPLETED" | "DEDUPLICATED";
            deduplicated: boolean;
        };
        OwnerMediaSummary: {
            /** Format: uuid */
            id: string;
            media_type: components["schemas"]["MediaType"];
            content_revision: number;
            /** Format: date-time */
            captured_at: string;
            /** Format: date-time */
            created_at: string;
        };
        OwnerMediaPage: {
            items: components["schemas"]["OwnerMediaSummary"][];
            next_cursor?: string;
        };
        PrivateMediaResource: {
            /** Format: uuid */
            resource_id: string;
            resource_type: components["schemas"]["MediaResourceType"];
            mime_type: string;
            content_size: number;
            /** @description Unpadded standard base64 SHA-256 digest. */
            content_sha256: string;
        };
        PrivateMediaSummary: {
            /** Format: uuid */
            id: string;
            media_type: components["schemas"]["MediaType"];
            /** Format: date-time */
            captured_at: string;
            /** Format: date-time */
            created_at: string;
            duration_ms?: number;
            original_total_size: number;
            preview_resource?: components["schemas"]["PrivateMediaResource"];
        };
        PrivateMediaPage: {
            items: components["schemas"]["PrivateMediaSummary"][];
            next_cursor?: string | null;
        };
        PrivateMediaDetail: {
            /** Format: uuid */
            id: string;
            media_type: components["schemas"]["MediaType"];
            /** Format: date-time */
            captured_at: string;
            /** Format: date-time */
            created_at: string;
            width?: number;
            height?: number;
            duration_ms?: number;
            original_total_size: number;
            resources: components["schemas"]["PrivateMediaResource"][];
        };
        PrivateMediaAccessRequest: {
            /** @enum {string} */
            purpose: "VIEW" | "STREAM" | "DOWNLOAD";
            /** @enum {string} */
            variant?: "THUMBNAIL" | "DETAIL";
        };
        PrivateMediaAccessResource: {
            /** Format: uuid */
            resource_id: string;
            resource_type: components["schemas"]["MediaResourceType"];
            mime_type: string;
            content_size: number;
            content_sha256: string;
            supports_range: boolean;
            /**
             * @description ORIGINAL_RESOURCE returns the registered bytes. OSS_IMAGE_THUMBNAIL returns an on-the-fly OSS image transformation of the registered ORIGINAL; content_size/content_sha256 describe that source object and must not be used to validate transformed bytes.
             * @enum {string}
             */
            delivery_mode: "ORIGINAL_RESOURCE" | "OSS_IMAGE_THUMBNAIL";
            /** @description Required for OSS_IMAGE_THUMBNAIL; the transformed image byte limit enforced by the client. */
            maximum_output_size?: number;
            grant: components["schemas"]["ObjectGrant"];
        };
        PrivateMediaAccessResult: {
            /** Format: uuid */
            media_id: string;
            /** @enum {string} */
            purpose: "VIEW" | "STREAM" | "DOWNLOAD";
            /** @enum {string} */
            variant?: "THUMBNAIL" | "DETAIL";
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
            resources: components["schemas"]["PrivateMediaAccessResource"][];
        };
        PrivateMediaTrashResult: {
            /** Format: uuid */
            media_id: string;
            /** @enum {string} */
            outcome: "TRASHED" | "ALREADY_TRASHED";
            /** Format: date-time */
            trashed_at: string;
        };
        SetPrivateMediaShareRequest: {
            shared: boolean;
        };
        PrivateMediaShareResult: {
            /** Format: uuid */
            media_id: string;
            /** @enum {string} */
            state: "ACTIVE" | "INACTIVE";
            /** @enum {string} */
            outcome: "SHARED" | "ALREADY_SHARED" | "UNSHARED" | "ALREADY_UNSHARED";
            /** Format: date-time */
            effective_at: string;
        };
        FamilyMediaOwner: {
            /** Format: uuid */
            id: string;
            nickname: string;
        };
        FamilyMediaSummary: {
            /** Format: uuid */
            id: string;
            owner: components["schemas"]["FamilyMediaOwner"];
            media_type: components["schemas"]["MediaType"];
            /** Format: date-time */
            captured_at: string;
            /** Format: date-time */
            created_at: string;
            duration_ms?: number;
            original_total_size: number;
        };
        FamilyMediaPage: {
            items: components["schemas"]["FamilyMediaSummary"][];
            next_cursor?: string | null;
        };
        FamilyMediaDetail: {
            /** Format: uuid */
            id: string;
            owner: components["schemas"]["FamilyMediaOwner"];
            media_type: components["schemas"]["MediaType"];
            /** Format: date-time */
            captured_at: string;
            /** Format: date-time */
            created_at: string;
            width?: number;
            height?: number;
            duration_ms?: number;
            original_total_size: number;
            resources: components["schemas"]["PrivateMediaResource"][];
        };
        FamilyMediaAccessRequest: {
            /** @enum {string} */
            purpose: "VIEW" | "STREAM";
            /** @enum {string} */
            variant?: "THUMBNAIL" | "DETAIL";
        };
        TrashMediaSummary: {
            /** Format: uuid */
            id: string;
            media_type: components["schemas"]["MediaType"];
            /** Format: date-time */
            captured_at: string;
            /** Format: date-time */
            created_at: string;
            duration_ms?: number;
            original_total_size: number;
            /** Format: date-time */
            trashed_at: string;
        };
        TrashMediaPage: {
            items: components["schemas"]["TrashMediaSummary"][];
            next_cursor?: string | null;
        };
        TrashMediaRestoreResult: {
            /** Format: uuid */
            media_id: string;
            /** @enum {string} */
            outcome: "RESTORED" | "ALREADY_RESTORED";
            /** Format: date-time */
            restored_at: string;
        };
        FAQItem: {
            id: string;
            question: string;
            answer: string;
        };
        FAQDocument: {
            version: string;
            items: components["schemas"]["FAQItem"][];
        };
        SubmitFeedbackRequest: {
            /** @enum {string} */
            category: "ACCOUNT" | "PERMISSION" | "BACKUP" | "BROWSE_PLAYBACK" | "SHARING" | "TRASH" | "OTHER";
            description: string;
            contact?: string;
            app_version: string;
            /** @enum {string} */
            platform: "ANDROID" | "IOS" | "HARMONYOS";
            os_version: string;
            device_installation_id: string;
        };
        SubmitFeedbackResult: {
            /** Format: uuid */
            feedback_id: string;
            /** @enum {string} */
            outcome: "SUBMITTED" | "ALREADY_SUBMITTED";
            /** Format: date-time */
            created_at: string;
        };
        AdminLoginRequest: {
            username: string;
            password: string;
        };
        AdminSessionResult: {
            csrf_token: string;
            username: string;
        };
        Approval: {
            /** Format: uuid */
            id: string;
            masked_phone: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSED";
            /** Format: date-time */
            created_at: string;
        };
        ApprovalPage: {
            items: components["schemas"]["Approval"][];
            next_cursor: string | null;
        };
        ApproveResult: {
            approval: components["schemas"]["Approval"];
            /** @enum {string} */
            outcome: "APPROVED" | "ALREADY_PROCESSED";
        };
        StatusMessage: {
            status: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            code: string;
            request_id: string;
            retryable: boolean;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description RFC 9457 problem details with stable MineG extensions. */
        Problem: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ApprovalId: string;
        UploadId: string;
        MediaId: string;
        Origin: string;
        CSRFToken: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation identifier generated or accepted by the service. */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is accepting HTTP requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    runPlatformProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API JSON and UTC timestamp contract is reachable. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProbe"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description A pending account was created, or the same idempotent result was recovered. Legacy key fields are optional compatibility input. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUpResult"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description A mobile session was created. Pending sessions are restricted to review status and logout operations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResult"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Access and refresh tokens were rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResult"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The current mobile session was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
        };
    };
    getApprovalStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product-visible approval status. Administrator approval transitions directly to APPROVED. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalStatus"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Minimal real profile for an approved member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description The current approved member nickname was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    createAvatarUpload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvatarUploadRequest"];
            };
        };
        responses: {
            /** @description A short-lived upload grant restricted to one avatar object was issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUploadResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    completeAvatarUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Object metadata was verified and the avatar became the current profile image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getAvatarReadGrant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A short-lived read grant for the current avatar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectGrant"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createMediaUpload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMediaUploadRequest"];
            };
        };
        responses: {
            /** @description A resumable original-media multipart session was created, replayed, or converged to an existing same-account media. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadSession"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getMediaUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped persisted upload truth. Object grants are omitted from status reads. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadSession"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    reportMediaUploadPart: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                upload_id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportMediaPartRequest"];
            };
        };
        responses: {
            /** @description The exact part ETag, content size, and digest were persisted; identical reports are idempotent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPartResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    completeMediaUpload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                upload_id: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteMediaUploadRequest"];
            };
        };
        responses: {
            /** @description OSS multipart state was verified and a completed owner media was committed transactionally. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteMediaUploadResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listCompletedOwnerMedia: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed metadata owned by the authenticated member; no object URL or key envelope is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerMediaPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listPrivateMedia: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped completed, non-trashed media in a stable HMAC-bound seek page; no object URL is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateMediaPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getPrivateMediaDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped media detail and registered resource metadata; object keys and grants are omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateMediaDetail"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    createPrivateMediaAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivateMediaAccessRequest"];
            };
        };
        responses: {
            /** @description A fresh, short-lived owner-scoped GET authorization. The caller must not persist the grants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateMediaAccessResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    trashPrivateMedia: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                media_id: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Media was logically trashed or the prior identical request was replayed. No OSS object is moved or removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateMediaTrashResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    setPrivateMediaShare: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                media_id: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPrivateMediaShareRequest"];
            };
        };
        responses: {
            /** @description The owner-scoped family visibility reached the requested state; repeat requests are idempotent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateMediaShareResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listFamilyMedia: {
        parameters: {
            query?: {
                filter?: "all" | "mine";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active, non-trashed media shared inside the fixed household; mine filters before pagination. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyMediaPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getFamilyMediaDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only metadata for an active fixed-household share; object keys are omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyMediaDetail"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    createFamilyMediaAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyMediaAccessRequest"];
            };
        };
        responses: {
            /** @description A short-lived read-only view or stream grant. Family access never supports DOWNLOAD. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateMediaAccessResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listTrashMedia: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active logical-trash records owned by the authenticated member, ordered by first trash time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashMediaPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    restoreTrashMedia: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                media_id: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description The media was restored to private state and remains unshared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashMediaRestoreResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getFAQ: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned FAQ compatibility payload. The App retains an offline copy of the same subjects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FAQDocument"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    submitFeedback: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitFeedbackRequest"];
            };
        };
        responses: {
            /** @description Feedback was stored once; a repeated identical request returns the existing identifier. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitFeedbackResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    adminSignIn: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Administrator session cookie was issued and a CSRF token returned. */
            200: {
                headers: {
                    /** @description Secure, HttpOnly, SameSite=Strict administrator session cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    restoreAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active session was restored and its CSRF token rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResult"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    adminSignOut: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator session was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending applications ordered oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPage"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked application detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    approveApplication: {
        parameters: {
            query?: never;
            header: {
                Origin: components["parameters"]["Origin"];
                "X-CSRF-Token": components["parameters"]["CSRFToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                approval_id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review decision is committed and the account becomes APPROVED. Repeats return ALREADY_PROCESSED. */
            200: {
                headers: {
                    /** @description Rotated CSRF token for the next state-changing request. */
                    "X-CSRF-Token"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResult"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
}
